from BinaryCrossEntropy import Loss_BinaryCrossEntropy
from CategoricalCrossEntropy import Loss_CategoricalCrossEntropy
from Loss import Loss
from MeanSquaredError import Loss_MeanSquaredError
from MeanAbsoluteError import Loss_MeanAbsoluteError